{
  imports = [
    ./bluetooth.nix
    ./bootloader.nix
    ./caps2esc.nix
    ./cloudflare-warp.nix
    ./desktop-environment-et-al.nix
    ./fish.nix
    ./fonts.nix
    ./games.nix
    ./i18n-l10n.nix
    ./networking.nix
    ./nix-alien.nix
    ./nvidia.nix
    ./partition-manager.nix
    ./pipewire.nix
    ./stylix.nix
    ./touchegg.nix
  ];
}
