{
  imports = [
    ./games
    ./bluetooth.nix
    ./bootloader.nix
    ./caps2esc.nix
    ./cloudflare-warp.nix
    ./fish.nix
    ./fonts.nix
    ./kde-plasma-5.nix
    ./i18n-l10n.nix
    ./networking.nix
    ./nix-alien.nix
    ./nvidia-driver.nix
    ./partition-manager.nix
    ./pipewire.nix
    ./stylix.nix
    ./touchegg.nix
  ];
}
